name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java Environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create Required Directories
        run: |
          mkdir -p lib bin

      - name: Download JUnit Platform Console Standalone
        run: |
          curl -L https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.11.4/junit-platform-console-standalone-1.11.4.jar -o lib/junit-platform-console-standalone-1.11.4.jar

      - name: Compile Source Files
        run: |
          javac -d bin src/*.java 

      - name: Compile Test Files
        run: |
          javac -d bin -cp bin:lib/junit-platform-console-standalone-1.11.4.jar test/*.java

      - name: Run Tests
        run: |
          java -jar lib/junit-platform-console-standalone-1.11.4.jar -cp bin --scan-class-path
